gestures:
  - midi:
      - channel: 1
        note: 60
      - channel: 1
        cc: 24
        axis: 'y'
        bottom: 0
        top: 127
        singleValue: false
      - channel: 1
        cc: 26
        axis: 'y'
        bottom: 0
        top: 127
        singleValue: false
    position:
      - true
      - 0.1
      - 50
      - 0.3
      - 300
    cv: []
  - midi:
      - channel: 2
        note: 62
      - channel: 1
        cc: 30
        axis: 'y'
        bottom: 0
        top: 127
        singleValue: false
      - channel: 1
        cc: 31
        axis: 'y'
        bottom: 0
        top: 127
        singleValue: false
    position:
      - true
      - 0.2
      - 100
      - 0.4
      - 400
    cv: []
  - midi:
      - channel: 1
        note: 64
      - channel: 1
        cc: 35
        axis: 'y'
        bottom: 0
        top: 127
        singleValue: false
      - channel: 1
        cc: 40
        axis: 'y'
        bottom: 0
        top: 127
        singleValue: false
    position:
      - true
      - 0.5
      - 70
      - 0.7
      - 250
    cv: []
  - midi:
      - channel: 3
        note: 65
      - channel: 1
        cc: 36
        axis: 'y'
        bottom: 0
        top: 127
        singleValue: false
      - channel: 1
        cc: 56
        axis: 'y'
        bottom: 0
        top: 127
        singleValue: false
    position:
      - true
      - 0.4
      - 150
      - 0.6
      - 350
    cv: []
  - midi:
      - channel: 4
        note: 67
      - channel: 1
        cc: 24
        axis: 'y'
        bottom: 0
        top: 127
        singleValue: false
      - channel: 1
        cc: 31
        axis: 'y'
        bottom: 0
        top: 127
        singleValue: false
    position:
      - true
      - 0.3
      - 80
      - 0.5
      - 300
    cv: []
  - midi:
      - channel: 3
        note: 69
      - channel: 1
        cc: 30
        axis: 'y'
        bottom: 0
        top: 127
        singleValue: false
      - channel: 1
        cc: 26
        axis: 'y'
        bottom: 0
        top: 127
        singleValue: false
    position:
      - true
      - 0
      - 200
      - 0.2
      - 600
    cv: []
  - midi:
      - channel: 2
        note: 71
      - channel: 1
        cc: 35
        axis: 'y'
        bottom: 0
        top: 127
        singleValue: false
      - channel: 1
        cc: 40
        axis: 'y'
        bottom: 0
        top: 127
        singleValue: false
    position:
      - true
      - 0.6
      - 100
      - 0.8
      - 300
    cv: []
  - midi:
      - channel: 2
        note: 72
      - channel: 1
        cc: 56
        axis: 'y'
        bottom: 0
        top: 127
        singleValue: false
      - channel: 1
        cc: 26
        axis: 'y'
        bottom: 0
        top: 127
        singleValue: false
    position:
      - true
      - 0.8
      - 50
      - 1
      - 700
    cv: []
  - midi:
      - channel: 3
        note: 74
      - channel: 1
        cc: 24
        axis: 'y'
        bottom: 0
        top: 127
        singleValue: false
      - channel: 1
        cc: 31
        axis: 'y'
        bottom: 0
        top: 127
        singleValue: false
    position:
      - true
      - 0.4
      - 200
      - 0.8
      - 600
    cv: []
  - midi:
      - channel: 1
        note: 76
      - channel: 1
        cc: 30
        axis: 'y'
        bottom: 0
        top: 127
        singleValue: false
      - channel: 1
        cc: 36
        axis: 'y'
        bottom: 0
        top: 127
        singleValue: false
    position:
      - true
      - 0.2
      - 300
      - 0.4
      - 500
    cv: []
